name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - config/**
      - src/**
      - phpstan*
      - tests/StaticAnalysis/**
  push:

jobs:
  static-analysis:
    uses: "doctrine/.github/.github/workflows/phpstan.yml@7.1.0"
